create table if not exists public.research_dictation_attempts (
  note_attempt_id text primary key,
  session_id text,
  participant_id text,
  class_group text,
  template_id text,
  word_id text,
  target_word text,
  slot_index int,
  retry_index int,
  judge_mode text,
  judge_status text,
  is_blank boolean,
  blank_score double precision,
  ink_ratio double precision,
  gate_grade int,
  gate_score double precision,
  gate_decision text,
  gate_pass_threshold int,
  gate_model_version text,
  verify_margin double precision,
  verify_free_conf double precision,
  verify_completeness double precision,
  verify_best_margin double precision,
  verify_decision text,
  verify_tau1 double precision,
  verify_tau2 double precision,
  verify_lambda double precision,
  ocr_raw_text text,
  spelling_correct boolean,
  jamo_edit_distance int,
  wrong_jamo_positions jsonb,
  estimated_written text,
  reward_level int,
  escape_used boolean,
  feedback_message text,
  crop_asset_id text,
  crop_sha256 text,
  scan_duration_ms int,
  gate_duration_ms int,
  ocr_duration_ms int,
  created_at bigint,
  raw_json jsonb,
  ingested_at timestamptz default now()
);
create index if not exists idx_rda_session on public.research_dictation_attempts(session_id);
create index if not exists idx_rda_participant on public.research_dictation_attempts(participant_id);
create index if not exists idx_rda_word on public.research_dictation_attempts(word_id);
alter table public.research_dictation_attempts enable row level security;
